import type { SQL } from 'bun'

/** Every table the seeder touches, children first so CASCADE has nothing left to chase. */
const TABLES = [
  'events',
  'dialog_state',
  'messages',
  'dialogs',
  'likes',
  'comments',
  'posts',
  'media',
  'community_members',
  'follows',
  'friendships',
  'communities',
  'notifications',
  'friend_suggestion_hidden',
  'users',
  'author_stats_daily',
  'user_profiles_ml',
  'friend_suggestions',
  'model_versions',
]

export async function resetDatabase(sql: SQL): Promise<void> {
  await sql.unsafe(`TRUNCATE ${TABLES.join(', ')} RESTART IDENTITY CASCADE`)
}

/**
 * The seeder inserts explicit ids into the identity columns (they are GENERATED BY DEFAULT),
 * which leaves the backing sequences at 1. Point them past the highest inserted id so the API's
 * own INSERTs do not collide. `setval(..., max+1, false)` makes `max+1` the next value handed out.
 */
export async function syncSequences(sql: SQL): Promise<void> {
  for (const t of ['users', 'communities', 'posts', 'comments', 'media']) {
    await sql.unsafe(
      `SELECT setval(pg_get_serial_sequence('${t}','id'), COALESCE((SELECT max(id) FROM ${t}), 0) + 1, false)`,
    )
  }
}

/** Denormalised counters, recomputed in bulk after the event tables are filled. */
export async function recomputeCounters(sql: SQL): Promise<void> {
  await sql`UPDATE posts p SET likes_count = s.n FROM (SELECT target_id, count(*)::int n FROM likes WHERE target_type='post' GROUP BY target_id) s WHERE s.target_id = p.id`
  await sql`UPDATE posts p SET comments_count = s.n FROM (SELECT post_id, count(*)::int n FROM comments GROUP BY post_id) s WHERE s.post_id = p.id`
  await sql`UPDATE posts p SET views_count = s.n FROM (SELECT post_id, count(*)::int n FROM events WHERE kind='view' GROUP BY post_id) s WHERE s.post_id = p.id`
  await sql`UPDATE communities c SET members_count = s.n FROM (SELECT community_id, count(*)::int n FROM community_members GROUP BY community_id) s WHERE s.community_id = c.id`
}
