CREATE TYPE "public"."author_type" AS ENUM('user', 'community');--> statement-breakpoint
CREATE TYPE "public"."event_kind" AS ENUM('view', 'like', 'comment', 'repost', 'click', 'hide');--> statement-breakpoint
CREATE TYPE "public"."follow_target" AS ENUM('user', 'community');--> statement-breakpoint
CREATE TYPE "public"."friendship_status" AS ENUM('pending', 'accepted', 'declined');--> statement-breakpoint
CREATE TYPE "public"."like_target" AS ENUM('post', 'comment');--> statement-breakpoint
CREATE TYPE "public"."media_kind" AS ENUM('photo', 'audio', 'avatar', 'cover');--> statement-breakpoint
CREATE TYPE "public"."member_role" AS ENUM('member', 'editor', 'admin');--> statement-breakpoint
CREATE TYPE "public"."model_kind" AS ENUM('feed_ranker', 'pymk_ranker');--> statement-breakpoint
CREATE TYPE "public"."topic" AS ENUM('cinema', 'music', 'memes', 'games', 'it', 'sport', 'travel', 'food', 'science', 'auto', 'fashion', 'city');--> statement-breakpoint
CREATE TABLE "users" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"login" varchar(64) NOT NULL,
	"password_hash" text NOT NULL,
	"first_name" varchar(64) NOT NULL,
	"last_name" varchar(64) NOT NULL,
	"screen_name" varchar(64),
	"status" varchar(140),
	"bio" text,
	"avatar_media_id" bigint,
	"cover_media_id" bigint,
	"birthday" date,
	"city" varchar(64),
	"is_verified" boolean DEFAULT false NOT NULL,
	"popularity_rank" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_seen_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "communities" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "communities_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"screen_name" varchar(64) NOT NULL,
	"name" varchar(120) NOT NULL,
	"description" text,
	"topic" "topic" NOT NULL,
	"avatar_media_id" bigint,
	"is_verified" boolean DEFAULT false NOT NULL,
	"members_count" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "community_members" (
	"community_id" bigint NOT NULL,
	"user_id" bigint NOT NULL,
	"role" "member_role" DEFAULT 'member' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "community_members_community_id_user_id_pk" PRIMARY KEY("community_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "follows" (
	"follower_id" bigint NOT NULL,
	"target_type" "follow_target" NOT NULL,
	"target_id" bigint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "follows_follower_id_target_type_target_id_pk" PRIMARY KEY("follower_id","target_type","target_id")
);
--> statement-breakpoint
CREATE TABLE "friendships" (
	"user_lo" bigint NOT NULL,
	"user_hi" bigint NOT NULL,
	"status" "friendship_status" NOT NULL,
	"requester_id" bigint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"accepted_at" timestamp with time zone,
	CONSTRAINT "friendships_user_lo_user_hi_pk" PRIMARY KEY("user_lo","user_hi")
);
--> statement-breakpoint
CREATE TABLE "comments" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "comments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"post_id" bigint NOT NULL,
	"author_id" bigint NOT NULL,
	"parent_id" bigint,
	"text" text NOT NULL,
	"likes_count" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "likes" (
	"user_id" bigint NOT NULL,
	"target_type" "like_target" NOT NULL,
	"target_id" bigint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "likes_user_id_target_type_target_id_pk" PRIMARY KEY("user_id","target_type","target_id")
);
--> statement-breakpoint
CREATE TABLE "media" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "media_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"owner_id" bigint NOT NULL,
	"kind" "media_kind" NOT NULL,
	"bucket" varchar(64) NOT NULL,
	"key" text NOT NULL,
	"content_hash" varchar(64),
	"width" integer,
	"height" integer,
	"duration" integer,
	"blurhash" varchar(64),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "posts" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "posts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"author_type" "author_type" NOT NULL,
	"author_id" bigint NOT NULL,
	"text" text NOT NULL,
	"topic" "topic",
	"attachments" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"likes_count" integer DEFAULT 0 NOT NULL,
	"comments_count" integer DEFAULT 0 NOT NULL,
	"reposts_count" integer DEFAULT 0 NOT NULL,
	"views_count" integer DEFAULT 0 NOT NULL,
	"embedding" vector(384),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "author_stats_daily" (
	"author_type" "author_type" NOT NULL,
	"author_id" bigint NOT NULL,
	"day" date NOT NULL,
	"posts" integer DEFAULT 0 NOT NULL,
	"likes" integer DEFAULT 0 NOT NULL,
	"comments" integer DEFAULT 0 NOT NULL,
	"views" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "author_stats_daily_author_type_author_id_day_pk" PRIMARY KEY("author_type","author_id","day")
);
--> statement-breakpoint
CREATE TABLE "friend_suggestions" (
	"user_id" bigint NOT NULL,
	"candidate_id" bigint NOT NULL,
	"score" double precision NOT NULL,
	"computed_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "friend_suggestions_user_id_candidate_id_pk" PRIMARY KEY("user_id","candidate_id")
);
--> statement-breakpoint
CREATE TABLE "model_versions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "model_versions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"kind" "model_kind" NOT NULL,
	"artifact_key" text NOT NULL,
	"metrics" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"trained_at" timestamp with time zone DEFAULT now() NOT NULL,
	"is_active" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_profiles_ml" (
	"user_id" bigint PRIMARY KEY NOT NULL,
	"interest_vector" vector(384),
	"topic_weights" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "dialog_state" (
	"dialog_id" bigint NOT NULL,
	"user_id" bigint NOT NULL,
	"last_read_local_id" integer DEFAULT 0 NOT NULL,
	"unread_count" integer DEFAULT 0 NOT NULL,
	"muted" boolean DEFAULT false NOT NULL,
	CONSTRAINT "dialog_state_dialog_id_user_id_pk" PRIMARY KEY("dialog_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "dialogs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "dialogs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_lo" bigint NOT NULL,
	"user_hi" bigint NOT NULL,
	"last_message_id" bigint,
	"last_local_id" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "messages" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "messages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"dialog_id" bigint NOT NULL,
	"dialog_local_id" integer NOT NULL,
	"sender_id" bigint NOT NULL,
	"text" text NOT NULL,
	"attachments" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"edited_at" timestamp with time zone,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "community_members" ADD CONSTRAINT "community_members_community_id_communities_id_fk" FOREIGN KEY ("community_id") REFERENCES "public"."communities"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "community_members" ADD CONSTRAINT "community_members_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "follows" ADD CONSTRAINT "follows_follower_id_users_id_fk" FOREIGN KEY ("follower_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "friendships" ADD CONSTRAINT "friendships_user_lo_users_id_fk" FOREIGN KEY ("user_lo") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "friendships" ADD CONSTRAINT "friendships_user_hi_users_id_fk" FOREIGN KEY ("user_hi") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "comments" ADD CONSTRAINT "comments_post_id_posts_id_fk" FOREIGN KEY ("post_id") REFERENCES "public"."posts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "comments" ADD CONSTRAINT "comments_author_id_users_id_fk" FOREIGN KEY ("author_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "likes" ADD CONSTRAINT "likes_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dialog_state" ADD CONSTRAINT "dialog_state_dialog_id_dialogs_id_fk" FOREIGN KEY ("dialog_id") REFERENCES "public"."dialogs"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dialog_state" ADD CONSTRAINT "dialog_state_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dialogs" ADD CONSTRAINT "dialogs_user_lo_users_id_fk" FOREIGN KEY ("user_lo") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dialogs" ADD CONSTRAINT "dialogs_user_hi_users_id_fk" FOREIGN KEY ("user_hi") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "messages" ADD CONSTRAINT "messages_dialog_id_dialogs_id_fk" FOREIGN KEY ("dialog_id") REFERENCES "public"."dialogs"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "messages" ADD CONSTRAINT "messages_sender_id_users_id_fk" FOREIGN KEY ("sender_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "users_login_uq" ON "users" USING btree ("login");--> statement-breakpoint
CREATE UNIQUE INDEX "users_screen_name_uq" ON "users" USING btree ("screen_name");--> statement-breakpoint
CREATE INDEX "users_city_idx" ON "users" USING btree ("city");--> statement-breakpoint
CREATE UNIQUE INDEX "communities_screen_name_uq" ON "communities" USING btree ("screen_name");--> statement-breakpoint
CREATE INDEX "communities_topic_idx" ON "communities" USING btree ("topic");--> statement-breakpoint
CREATE INDEX "community_members_user_idx" ON "community_members" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "follows_target_idx" ON "follows" USING btree ("target_type","target_id");--> statement-breakpoint
CREATE INDEX "friendships_hi_idx" ON "friendships" USING btree ("user_hi","status");--> statement-breakpoint
CREATE INDEX "friendships_lo_idx" ON "friendships" USING btree ("user_lo","status");--> statement-breakpoint
CREATE INDEX "comments_post_idx" ON "comments" USING btree ("post_id","id");--> statement-breakpoint
CREATE INDEX "likes_target_idx" ON "likes" USING btree ("target_type","target_id");--> statement-breakpoint
CREATE INDEX "media_hash_idx" ON "media" USING btree ("content_hash");--> statement-breakpoint
CREATE INDEX "posts_author_created_idx" ON "posts" USING btree ("author_type","author_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "posts_created_idx" ON "posts" USING btree ("created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "posts_embedding_hnsw" ON "posts" USING hnsw ("embedding" vector_cosine_ops);--> statement-breakpoint
CREATE INDEX "user_profiles_ml_vec_hnsw" ON "user_profiles_ml" USING hnsw ("interest_vector" vector_cosine_ops);--> statement-breakpoint
CREATE INDEX "dialog_state_user_idx" ON "dialog_state" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "dialogs_pair_uq" ON "dialogs" USING btree ("user_lo","user_hi");--> statement-breakpoint
CREATE UNIQUE INDEX "messages_dialog_local_uq" ON "messages" USING btree ("dialog_id","dialog_local_id");