CREATE TABLE "events" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" bigint NOT NULL,
  "post_id" bigint NOT NULL,
  "kind" "event_kind" NOT NULL,
  "source" varchar(32) NOT NULL,
  "position" integer DEFAULT 0 NOT NULL,
  "session_id" bigint NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY ("id", "created_at")
) PARTITION BY RANGE ("created_at");
--> statement-breakpoint
CREATE TABLE "events_default" PARTITION OF "events" DEFAULT;
--> statement-breakpoint
CREATE OR REPLACE FUNCTION ensure_events_partitions(from_month date, to_month date) RETURNS void AS $$
DECLARE m date := date_trunc('month', from_month)::date;
BEGIN
  WHILE m <= to_month LOOP
    EXECUTE format('CREATE TABLE IF NOT EXISTS %I PARTITION OF events FOR VALUES FROM (%L) TO (%L)',
      'events_' || to_char(m, 'YYYY_MM'), m, (m + interval '1 month')::date);
    m := (m + interval '1 month')::date;
  END LOOP;
END $$ LANGUAGE plpgsql;
--> statement-breakpoint
SELECT ensure_events_partitions((current_date - interval '6 months')::date, (current_date + interval '3 months')::date);
--> statement-breakpoint
CREATE INDEX "events_user_created_idx" ON "events" ("user_id", "created_at");
--> statement-breakpoint
CREATE INDEX "events_post_idx" ON "events" ("post_id");
--> statement-breakpoint
CREATE INDEX "events_session_idx" ON "events" ("session_id");
