-- `events` is RANGE-partitioned by `created_at`, one partition per month.
--
-- Coverage: the `SELECT ensure_events_partitions(...)` below runs at MIGRATION time, so it only
-- creates partitions for [migration month - 6, migration month + 3]. It does NOT roll forward on
-- its own — a deployment left running past that window keeps writing, but into `events_default`.
--
-- `events_default` is the safety net that keeps such writes from failing. It is NOT a place to
-- leave rows: Postgres refuses to attach a partition for a range that the DEFAULT partition
-- already holds rows for. So before creating the partition for a month that has rows in
-- `events_default`, those rows must be moved out first:
--
--   BEGIN;
--   ALTER TABLE events DETACH PARTITION events_default;
--   CREATE TABLE events_YYYY_MM PARTITION OF events FOR VALUES FROM ('YYYY-MM-01') TO ('YYYY-MM+1-01');
--   INSERT INTO events SELECT * FROM events_default WHERE created_at >= 'YYYY-MM-01' AND created_at < 'YYYY-MM+1-01';
--   DELETE FROM events_default WHERE created_at >= 'YYYY-MM-01' AND created_at < 'YYYY-MM+1-01';
--   ALTER TABLE events ATTACH PARTITION events_default DEFAULT;
--   COMMIT;
--
-- Callers that write outside the migration-time window must therefore call
-- `ensure_events_partitions(from_month, to_month)` themselves BEFORE inserting — the seeder does
-- this for its own [SEED_NOW - days, SEED_NOW] window. The recurring roll-forward job that keeps
-- the window ahead of `now()` in a running deployment belongs to subsystem 3 (analytics).

CREATE TABLE "events" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" bigint NOT NULL,
  "post_id" bigint NOT NULL,
  "kind" "event_kind" NOT NULL,
  "source" varchar(32) NOT NULL,
  "position" integer DEFAULT 0 NOT NULL,
  "session_id" bigint NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY ("id", "created_at")
) PARTITION BY RANGE ("created_at");
--> statement-breakpoint
CREATE TABLE "events_default" PARTITION OF "events" DEFAULT;
--> statement-breakpoint
CREATE OR REPLACE FUNCTION ensure_events_partitions(from_month date, to_month date) RETURNS void AS $$
DECLARE m date := date_trunc('month', from_month)::date;
BEGIN
  WHILE m <= to_month LOOP
    EXECUTE format('CREATE TABLE IF NOT EXISTS %I PARTITION OF events FOR VALUES FROM (%L) TO (%L)',
      'events_' || to_char(m, 'YYYY_MM'), m, (m + interval '1 month')::date);
    m := (m + interval '1 month')::date;
  END LOOP;
END $$ LANGUAGE plpgsql;
--> statement-breakpoint
SELECT ensure_events_partitions((current_date - interval '6 months')::date, (current_date + interval '3 months')::date);
--> statement-breakpoint
CREATE INDEX "events_user_created_idx" ON "events" ("user_id", "created_at");
--> statement-breakpoint
CREATE INDEX "events_post_idx" ON "events" ("post_id");
--> statement-breakpoint
CREATE INDEX "events_session_idx" ON "events" ("session_id");
