CREATE EXTENSION IF NOT EXISTS pg_trgm;--> statement-breakpoint
CREATE TYPE "public"."notification_kind" AS ENUM('friend_request', 'friend_accepted', 'new_follower', 'community_invite', 'post_like', 'comment_like', 'post_comment', 'comment_reply', 'mention', 'repost', 'community_post', 'birthday');--> statement-breakpoint
CREATE TABLE "friend_suggestion_hidden" (
	"user_id" bigint NOT NULL,
	"hidden_id" bigint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "friend_suggestion_hidden_user_id_hidden_id_pk" PRIMARY KEY("user_id","hidden_id")
);
--> statement-breakpoint
CREATE TABLE "notifications" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "notifications_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"kind" "notification_kind" NOT NULL,
	"actor_id" bigint,
	"group_key" varchar(128),
	"payload" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"read_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "friend_suggestion_hidden" ADD CONSTRAINT "friend_suggestion_hidden_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "friend_suggestion_hidden" ADD CONSTRAINT "friend_suggestion_hidden_hidden_id_users_id_fk" FOREIGN KEY ("hidden_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_actor_id_users_id_fk" FOREIGN KEY ("actor_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "notifications_user_id_idx" ON "notifications" USING btree ("user_id","id" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "notifications_unread_idx" ON "notifications" USING btree ("user_id") WHERE "notifications"."read_at" is null;--> statement-breakpoint
CREATE INDEX "users_name_trgm" ON "users" USING gin (lower("first_name" || ' ' || "last_name") gin_trgm_ops);--> statement-breakpoint
CREATE INDEX "users_screen_name_trgm" ON "users" USING gin (lower("screen_name") gin_trgm_ops);--> statement-breakpoint
CREATE INDEX "communities_name_trgm" ON "communities" USING gin (lower("name") gin_trgm_ops);--> statement-breakpoint
CREATE INDEX "friendships_requester_idx" ON "friendships" USING btree ("requester_id","status");