import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

export function buildSprite(svgRoot: string): { sprite: string; names: string[] } {
  const names: string[] = []
  const symbols: string[] = []
  const sizes = readdirSync(svgRoot)
    .filter((d) => /^\d+$/.test(d))
    .sort((a, b) => Number(a) - Number(b))
  for (const size of sizes) {
    const dir = join(svgRoot, size)
    for (const file of readdirSync(dir)
      .filter((f) => f.endsWith('.svg'))
      .sort()) {
      const name = file.replace(/\.svg$/, '')
      const raw = readFileSync(join(dir, file), 'utf8').trim()
      const open = raw.match(/^(?:<\?xml[^>]*\?>\s*)?<svg\b([^>]*)>/)
      if (!open) throw new Error(`bad svg: ${file}`)
      const attrs = open[1] ?? ''
      const viewBox = attrs.match(/viewBox="([^"]+)"/)?.[1] ?? `0 0 ${size} ${size}`
      const fill = attrs.match(/\bfill="([^"]+)"/)?.[1]
      let inner = raw.slice(open[0].length).replace(/<\/svg>\s*$/, '')
      inner = inner
        .replace(/\bid="([^"]+)"/g, (_, id: string) => `id="${name}-${id}"`)
        .replace(/url\(#([^)]+)\)/g, (_, id: string) => `url(#${name}-${id})`)
        .replace(/\bhref="#([^"]+)"/g, (_, id: string) => `href="#${name}-${id}"`)
      const fillAttr = fill ? ` fill="${fill}"` : ''
      symbols.push(`<symbol id="${name}" viewBox="${viewBox}"${fillAttr}>${inner}</symbol>`)
      names.push(name)
    }
  }
  const sprite = `<svg xmlns="http://www.w3.org/2000/svg" style="display:none">${symbols.join('')}</svg>\n`
  return { sprite, names }
}

export function renderNames(names: string[]): string {
  const union = names.map((n) => `  | '${n}'`).join('\n')
  return `// generated by scripts/build-icons.ts, do not edit\nexport type IconName =\n${union}\n\nexport const ICON_NAMES = [\n${names.map((n) => `  '${n}',`).join('\n')}\n] as const satisfies readonly IconName[]\n`
}

if (import.meta.main) {
  const here = dirname(fileURLToPath(import.meta.url))
  const pkgRoot = join(here, '..')
  const candidates = [
    join(pkgRoot, 'node_modules/@vkontakte/icons/src/svg'),
    join(pkgRoot, '../../node_modules/@vkontakte/icons/src/svg'),
  ]
  const svgRoot = candidates.find((c) => existsSync(c))
  if (!svgRoot) throw new Error('@vkontakte/icons not installed')
  const { sprite, names } = buildSprite(svgRoot)
  writeFileSync(join(pkgRoot, 'src/icons/sprite.svg'), sprite)
  writeFileSync(join(pkgRoot, 'src/icons/names.ts'), renderNames(names))
  console.log(`icons: ${names.length} symbols, ${(sprite.length / 1024).toFixed(0)} KB`)
}
